### ISSUE TITLE
2번째 파라미터부터는 suggestion이 작동하지 않음.

### ISSUE THREAD

**Issue by ssyuk** [kimsyuk/shuffle#21]
ex) shfl apps 까지는 suggestion이 작동, add부터는 suggestion이 작동하지 않음.

**Comment by norhu1130** [comment]
@ssyuk 이슈 종료 안됨.
의도된 동작?

**Comment by ssyuk** [comment]
> @ssyuk 이슈 종료 안됨.
> 
> 의도된 동작?

yes
